databases:
  - name: jar-database
    plan: free
    databaseName: jar_db
    user: jar_user

services:
  - type: web
    name: 90s-jar
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: jar-database
          property: connectionString
